services:
  - type: web
    name: pincode-crawler
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: TOMTOM_API_KEY
        sync: false
